//AUTO GENERATED BY PYTHON SCRIPT
#pragma once
#include <stdint.h>
#include <stddef.h>
#include "map"
#include "string"

struct EMBEDDED_FILE_STRUCT {
	const uint8_t* data;
	const size_t size;
};
std::map<std::string, EMBEDDED_FILE_STRUCT> FILE_MAPPING = {
};